# vim: set ft=ruby :
# GENERATED BY RAILS TEMPLATE

require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/rails'
require 'capistrano/sidekiq'
Dir.glob('lib/capistrano/tasks/*.cap').each {|r| import r}
