# vi: set ft=ruby :
# GENERATED BY RAILS TEMPLATE

def cache config, name, path
  require 'fileutils'
  require 'pathname'
  name = name.to_s
  local = File.join(File.expand_path('~/.vagrant.d/cache'), config.vm.box, name)
  FileUtils.mkdir_p local
  config.vm.synced_folder local, path
end

Vagrant.configure(api_version='2') do |config|
  config.vm.define('inquisitor') do |app|
    app.vm.box = 'ubuntu/trusty64'

    app.vm.provider 'virtualbox' do |box|
      box.memory = 2048
    end

    app.vm.synced_folder '.', '/home/vagrant/inquisitor'

    app.vm.network :forwarded_port, guest: 3000, host: 3000 # app

    app.ssh.forward_agent = true

    cache app, :apt, '/var/cache/apt/archives'
    cache app, :chef, '/var/chef/cache'
    cache app, :gem, '/var/lib/gems/2.2.0/cache'

    app.vm.provision :chef_solo do |chef|
      chef.run_list = ['inquisitor::development']
    end
  end
end
