# GENERATED BY RAILS TEMPLATE
name             'inquisitor'
maintainer       'Chase Southard'
maintainer_email 'chase.southard@gmail.com'
license          'All rights reserved'
description      'Installs and configures inquisitor'
long_description 'Installs and configures inquisitor'
version          '0.0.1'

supports 'ubuntu'

# Track dependencies for berkself
depends 'annoyances'
depends 'build-essential'
